### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by vick25** [hopollo/OBS-Youtube-Player#10]
I want to show the controls but adding **controls=1** or **controls=true** does not work. What have I missed to add?
Thanks

https://hopollo.github.io/OBS-Youtube-Player/?watch?v=Z2qOwI3c09c&controls=true&volume=100&loop=true&quality=hd720&forcequality=true&hideWhenStopped=true

**Comment by hopollo** [comment]
Hi,

There is no "controls" option available inside the link parameters

Controls are hidden by default in the "main core".

Not sure why you want the display controls tbh.

I will add the controls=true|false option soon
