### ISSUE TITLE
Height/Width values remain at default when changed

### ISSUE THREAD

**Issue by CrawfordK** [hopollo/OBS-Youtube-Player#14]
As the title states even when I update the height/Width it stays to the defaults.

**Comment by Fluffy-axoFox** [comment]
There is a mistake in the readme. Replace &width=VALUE and &height=VALUE with &w=VALUE and &h=VALUE

**Comment by hopollo** [comment]
Hi, i updated the readme (description) to avoid these in the future

https://github.com/hopollo/OBS-Youtube-Player/commit/5987e493d14a7052a0cdbfe57354aeb06aa1ce18
